language: python
services:
  - redis-server
env:
  global:
    - REDIS_HOST=localhost
    - DOCKER_COMPOSE_VERSION=1.23.2
python:
  - "3.6-dev"
before_install:
  # install docker compose
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
  - flake8 .
  - python3 -m pytest --cov-report=xml --cov=. tests/
  - docker-compose -f docker/compose-test.yml up --build --abort-on-container-exit --exit-code-from telegram-bot-test
after_success:
  - codecov
