version: '3.7'

# use this file for testing only

services:
  telegram-bot-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: artslob/telegram-bot:test
    networks:
      - test_network
    depends_on:
      - redis-test
    environment:
      - REDIS_HOST=redis-test
    command: python3 -m pytest tests/ -s
  redis-test:
    image: redis:5.0.3-alpine
    hostname: redis
    networks:
      - test_network

networks:
  test_network:
